"""
This script uses the pkl file previously generated by individual_spread

"""

#%%

# User input
hemi = "rh"
base_dir = "C:/meg/params/03_lh_rh_rerun"

# Import packages
import mne
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.neighbors import NearestNeighbors
import sys
import math as math
import nibabel.freesurfer.io as fs
from collections import Counter
from sklearn.metrics import silhouette_score, davies_bouldin_score
import pathlib as Path
import os
sys.path.append(os.path.join(base_dir, "python_scripts"))
import st_dbscan as st


#----- LOAD DATAFRAMES -----
# Load dataframe created in individual_spread.py
# This contains coordinates (x, y, and z) representing the center of mass for all subjects and frequencies 

# NORMALIZED DATA
with open(os.path.join(base_dir, f"COM_coord_subject_df_8_to_30_normalized_{hemi}.pkl"), "rb") as f:
   COM_coord_subject_df_normalized = pickle.load(f)

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data_normed = COM_coord_subject_df_normalized.loc[:, ['freq','x','y','z']].values

# UNNORMALIZED DATA
with open(os.path.join(base_dir, f"COM_coord_subject_df_8_to_30_{hemi}.pkl"), "rb") as f:
   COM_coord_subject_df = pickle.load(f)

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data = COM_coord_subject_df.loc[:, ['freq','x','y','z']].values


# %%
#----- USE PARAMETERS FROM LH  -----

best_eps1 = 0.0319
best_eps2 = 0.5
best_minpts = 9
hemi = "rh"
# This will be useful later on
filename = f"{hemi}_8-30Hz_bestparams_" + str(best_minpts) + "_" + str(best_eps1) + "_" + str(best_eps2)

#%%
st_dbscan = st.ST_DBSCAN(eps1 = best_eps1, eps2 = best_eps2, min_samples = best_minpts) 
st_dbscan.fit(data_normed)
mylabels = st_dbscan.labels

with open(f"{base_dir}/labels_" + filename + ".pkl", "wb") as f:
    pickle.dump(mylabels, f)



#%%
#----- PREPARE LABELS -----

with open(f"{base_dir}/labels_" + filename + ".pkl", "rb") as f:
   mylabels = pickle.load(f)

#%%
#----- VIEW DATA -----
def plot(data, labels, savedir=f"{base_dir}/dbscan/" + filename + ".png"):
    fig = plt.figure()
    ax = fig.add_subplot(1, 2, 2, projection='3d')

    colors = ['#E39911',  '#1A1AE7'] + ['#88837B'] * 20
    noise_color = "#88837B"

    # Build one color array for ALL points, in the same order as `data`
    point_colors = np.array([
        colors[lbl % len(colors)] if lbl != -1 else noise_color
        for lbl in labels
    ])
    print(point_colors)

    # Single scatter call -> matplotlib depth-sorts all points together
    ax.scatter(
        xs=data[:, 0], ys=data[:, 1], zs=data[:, 2],
        c=point_colors, s=0.4, alpha=0.4
    )

    ax.set_zlabel("z (inferior-superior)")
    ax.set_ylabel("y (posterior-anterior)")
    ax.set_xlim(-100, 100)
    ax.set_xticks([])
    ax.set_xticklabels([])
    ax.set_ylim(-100, 100)
    ax.set_yticks([-50, 0, 50])
    ax.set_yticklabels(["-50", "0", "50"])
    ax.set_zlim(-100, 100)
    ax.set_zticks([-50, 0, 50])
    ax.set_zticklabels(["-50", "0", "50"])
    ax.view_init(azim=0, elev=0)
    ax.set_box_aspect((1, 1, 1))
    fig.savefig("C:/meg/SpatioSpec_results_images/clusters_rh", dpi=600, bbox_inches="tight", pad_inches=1)

plot(data[:, 1:], mylabels)


# %%
#----- LEARN ABOUT LABELS ------

def percentage_table(arr):
    total = len(arr)
    freq = Counter(arr)
    table = [(num, (count / total) * 100) for num, count in freq.items()]
    table.sort(key=lambda x: -x[1])
    return table

arr = mylabels
for num, perc in percentage_table(arr):
    print(f"{num}: {perc:.2f}%")


#%%
#----- COLOUR BIG CLUSTERS BY FREQUENCY -----

# Extract just data associated with red
mask = mylabels == 0 # red label
labels_red = mylabels[mask]
data_red = data[mask]

# Extract just data associated with green
mask = mylabels == 1 # green label
labels_green = mylabels[mask]
data_green = data[mask]

# Plot and colour by frequency
def plot_color_by_freq(data, savedir): 
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
   
    ax.scatter(xs = data[:, 1], ys = data[:, 2], zs = data[:, 3], c = data[:, 0], cmap = 'viridis', s = 1)

    ax.set_zlabel("z (up)")
    ax.set_xlabel(f"x (right), on {hemi}")
    ax.set_ylabel("y (front)")
    ax.set_xlim(-100, 100)
    ax.set_ylim(-100, 100)
    ax.set_zlim(-100, 100)
    ax.view_init(azim=20, elev=0)
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)
    plt.ion()
    
plot_color_by_freq(data, f"{base_dir}/dbscan/" + filename + "_large.png")



#%%
import matplotlib.colors as mcolors


def smooth(mean_dims, mean_dim): 
    if len(mean_dims) >= 4:
        smoothed = np.mean([mean_dims[-1], mean_dims[-2], mean_dims[-3], mean_dims[-4], mean_dim])
    elif len(mean_dims) >= 3:
        smoothed = np.mean([mean_dims[-1], mean_dims[-2], mean_dims[-3], mean_dim])
    elif len(mean_dims) >= 2:
        smoothed = np.mean([mean_dims[-1], mean_dims[-2], mean_dim])
    elif len(mean_dims) == 1:
        smoothed = np.mean([mean_dims[-1], mean_dim])
    else:
        smoothed = mean_dim
    return smoothed


cmap = plt.get_cmap('viridis')
norm = mcolors.Normalize(vmin=0, vmax=88 - 1)

fig, ax = plt.subplots()

def one_plot(dim): 
    mean_dims = []
    se_dims = []
    colors =[]
    freqs = np.arange(8, 30, 0.25)
    for i in range(len(freqs)): 
        freq = freqs[i]
        rgba = cmap(norm(i))
        color = mcolors.to_hex(rgba)
        relevant = data[data[:, 0] == freq]
        mean_dim = np.mean(relevant[:,dim])
        mean_dims.append(smooth(mean_dims, mean_dim))
        mean_dims.append(smooth(mean_dims, mean_dim))
        mean_dims.append(smooth(mean_dims, mean_dim))
        mean_dims.append(smooth(mean_dims, mean_dim))
        se_dim = np.std(relevant[:,dim])/np.sqrt(604)
        se_dims.append(smooth(se_dims, se_dim))
        se_dims.append(smooth(se_dims, se_dim))
        se_dims.append(smooth(se_dims, se_dim))
        se_dims.append(smooth(se_dims, se_dim))
        colors.append(color)
        colors.append(color)
        colors.append(color)
        colors.append(color)
    ax.errorbar(x=np.arange(8, 30, 0.0625), y=mean_dims, yerr=se_dims, color="grey", ecolor='grey', elinewidth=1, capsize=0, zorder=1)
    ax.scatter(np.arange(8, 30, 0.0625), mean_dims, c=np.arange(8, 30, 0.0625), cmap='viridis', zorder=30, s=100)

one_plot(1)
one_plot(2)
one_plot(3)

ax.set_ylim(-75, 75)
ax.set_xlim(8, 30)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
#ax.spines['bottom'].set_visible(False)
#ax.spines['left'].set_visible(False)
ax.tick_params(axis='both', labelsize=18)
ax.set_yticks([-50, 0, 50])
ax.set_xticks([])
plt.savefig('C:/meg/SpatioSpec_results_images/y.png', transparent=True) 
plt.show()




# %%
import mne
stc = mne.read_source_estimate("C:/meg/params/mean_stc")
stc.plot(
    subject = "fsaverage", 
    subjects_dir = "C:/meg/params/fs_subjects", 
    time_viewer = True, 
    hemi = "rh"
)

# %%
# Histogram of cluster 1 labels
mask = mylabels == 1
labels_large = mylabels[mask]
data_large = data[mask]

n_bins = 88

fig, ax = plt.subplots()

counts, bin_edges, patches = ax.hist(data_large[:, 0], bins=n_bins)

# color bars left (purple) to right (yellow) using viridis
cmap = plt.get_cmap("viridis")
norm_positions = np.linspace(0, 1, n_bins)
for pos, patch in zip(norm_positions, patches):
    patch.set_facecolor(cmap(pos))

# axis limits
ax.set_xlim(8, 30)

# evenly spaced tick labels, skipping by 2
ax.set_xticks(np.arange(8, 31, 2))

# increase tick and label size
ax.tick_params(axis='both', labelsize=18)
#ax.set_xlabel("Frequency (Hz)", fontsize=16)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
#ax.spines['bottom'].set_visible(False)
#ax.spines['left'].set_visible(False)

# hide y ticks only, keep the x ticks we just set
ax.set_yticks([])
ax.set_xticks([])

plt.show()