"""
This script uses the pkl file previously generated by 1205_individual_spread

"""

#%%
# Import packages
import mne
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.neighbors import NearestNeighbors
import sys
sys.path.append("C:/meg/params/python_scripts")
import st_dbscan as st
import math as math
import nibabel.freesurfer.io as fs
from collections import Counter
from sklearn.metrics import silhouette_score, davies_bouldin_score
from datetime import datetime

# %%
#----- LOAD DATAFRAMES -----
# Load dataframe created in 1205_individual_spread.py
# This contains coordinates (x, y, and z) representing the center of mass for all subjects and frequencies 

# NORMALIZED DATA
file = "C:/meg/params/COM_coord_subject_df_8_to_30_normalized.pkl"
with open(file, "rb") as f:
   COM_coord_subject_df_normalized = pickle.load(f)

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data_normed = COM_coord_subject_df_normalized.loc[:, ['freq','x','y','z']].values

# UNNORMALIZED DATA
with open("C:/meg/params/COM_coord_subject_df_8_to_30.pkl", "rb") as f:
   COM_coord_subject_df = pickle.load(f)

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data = COM_coord_subject_df.loc[:, ['freq','x','y','z']].values

# %%
"""
----- CHOOSE PARAMETERS -----

SOURCES: 
https://towardsdatascience.com/gridsearchcv-for-beginners-db48a90114ee/
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

There exists a GridSearchCV sklearn function, but is difficult to use here because it expects that your estimator is a sklearn-estimator and has expected methods

SCORER
First tried silhouette score, but it consistently didn't work (negative), likely because
the silhouette score is no good for varying densities and shapes
Next tried the Davies-Bouldin index
https://en.wikipedia.org/wiki/Cluster_analysis#Davies%E2%80%93Bouldin_index 
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.davies_bouldin_score.html
Lower means better clustering

-----STARTING PARAMETERS -----

Previously chosen using the heuristic described in the original paper

For normalized data with frequency range 8 to 30 Hz: 
minpts = 10
eps1 = 0.03
eps2 = 0.5

----- WORKFLOW USED AND RESULTS -----
1. Use default params but search through eps2
eps1 = [0.03]
eps2 = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]
minpts = [10]
Now working on: eps1 0.03 eps2 0.25 minpts 10
Score: 4.350747423795681 # BEST
Now working on: eps1 0.03 eps2 0.5 minpts 10
Score: 4.3873258733490275
Now working on: eps1 0.03 eps2 0.75 minpts 10
Score: 5.7585727720990505
Now working on: eps1 0.03 eps2 1 minpts 10
Score: 6.101165575543418
Now working on: eps1 0.03 eps2 1.25 minpts 10
Score: 5.738114142413983
Now working on: eps1 0.03 eps2 1.5 minpts 10
Score: 6.188671509018757
Now working on: eps1 0.03 eps2 1.75 minpts 10
Score: 6.259681969811518

2. Search through eps1
eps1 = [0.2, 0.25, 0.03, 0.035, 0.04]
eps2 = [0.25]
minpts = [10]
    eps1  eps2  minpts      score
0  0.020  0.25    10.0   5.625463
1  0.020  0.50    10.0  11.020820
2  0.025  0.25    10.0   4.516958
3  0.025  0.50    10.0   5.175158
4  0.030  0.25    10.0   4.350747 # BEST (wow! heuristic was right!)
5  0.030  0.50    10.0   4.387326
6  0.035  0.25    10.0   4.719836
7  0.035  0.50    10.0   4.139096
8  0.040  0.25    10.0   3.678042
9  0.040  0.50    10.0   4.196310

3. Search through minpts
   eps1  eps2  minpts     score
0  0.03  0.25     6.0  7.087710
1  0.03  0.25     7.0  3.944734 # Lower is better; interesting
2  0.03  0.25     8.0  3.978660
3  0.03  0.25     9.0  4.321888
0  0.03  0.25     9.0  4.321888
1  0.03  0.25    10.0  4.350747
2  0.03  0.25    11.0  4.411247

4. Search through all three params around the values identified so far
eps1 = [0.027, 0.028, 0.029, 0.03, 0.031, 0.032, 0.033]
eps2 = [0.25, 0.5]
minpts = [7, 8, 9, 10, 11]
     eps1  eps2  minpts     score
     eps1  eps2  minpts     score
57  0.032  0.50     9.0  3.736510 
56  0.032  0.50     8.0  3.892654
69  0.033  0.50    11.0  3.911307
67  0.033  0.50     9.0  3.916098
42  0.031  0.25     9.0  3.928217
30  0.030  0.25     7.0  3.944734
31  0.030  0.25     8.0  3.978660
20  0.029  0.25     7.0  3.989955
64  0.033  0.25    11.0  4.083198
37  0.030  0.50     9.0  4.117724
47  0.031  0.50     9.0  4.153316
68  0.033  0.50    10.0  4.164689
59  0.032  0.50    11.0  4.171942
13  0.028  0.25    10.0  4.190154
46  0.031  0.50     8.0  4.230642
21  0.029  0.25     8.0  4.236943
63  0.033  0.25    10.0  4.240784
10  0.028  0.25     7.0  4.241065
29  0.029  0.50    11.0  4.264506
24  0.029  0.25    11.0  4.289068
66  0.033  0.50     8.0  4.313247
32  0.030  0.25     9.0  4.321888
65  0.033  0.50     7.0  4.337405
22  0.029  0.25     9.0  4.342443
33  0.030  0.25    10.0  4.350747
12  0.028  0.25     9.0  4.370879
11  0.028  0.25     8.0  4.375692
17  0.028  0.50     9.0  4.376526
38  0.030  0.50    10.0  4.387326
9   0.027  0.50    11.0  4.401558
34  0.030  0.25    11.0  4.411247
49  0.031  0.50    11.0  4.422818
27  0.029  0.50     9.0  4.444734
3   0.027  0.25    10.0  4.469823
39  0.030  0.50    11.0  4.475046
1   0.027  0.25     8.0  4.489380
14  0.028  0.25    11.0  4.491973
36  0.030  0.50     8.0  4.504918
0   0.027  0.25     7.0  4.512836
19  0.028  0.50    11.0  4.516570
53  0.032  0.25    10.0  4.519937
48  0.031  0.50    10.0  4.546324
18  0.028  0.50    10.0  4.547342
52  0.032  0.25     9.0  4.567168
23  0.029  0.25    10.0  4.568595
6   0.027  0.50     8.0  4.573555
28  0.029  0.50    10.0  4.578406
54  0.032  0.25    11.0  4.641660
55  0.032  0.50     7.0  4.644976
2   0.027  0.25     9.0  4.659567
26  0.029  0.50     8.0  4.671388
44  0.031  0.25    11.0  4.708997
8   0.027  0.50    10.0  4.771337
58  0.032  0.50    10.0  4.775329
43  0.031  0.25    10.0  4.789418
45  0.031  0.50     7.0  4.873275
60  0.033  0.25     7.0  4.873534
62  0.033  0.25     9.0  4.876818
7   0.027  0.50     9.0  4.908530
16  0.028  0.50     8.0  4.946226
40  0.031  0.25     7.0  4.950558
41  0.031  0.25     8.0  4.978520
5   0.027  0.50     7.0  4.995465
35  0.030  0.50     7.0  5.004874
50  0.032  0.25     7.0  5.100627
15  0.028  0.50     7.0  5.112060
61  0.033  0.25     8.0  5.141475
51  0.032  0.25     8.0  5.171095
25  0.029  0.50     7.0  5.184949
4   0.027  0.25    11.0  5.268355

5. Narrow down eps1
eps1 = [0.0319, 0.0318, 0.0317, 0.0316, 0.032, 0.0321, 0.0322, 0.0323, 0.0324]
eps2 = [0.5]
minpts = [8, 9]
      eps1  eps2  minpts     score
1   0.0319   0.5     9.0  3.636312 # BEST!!!
3   0.0318   0.5     9.0  3.668517
5   0.0317   0.5     9.0  3.675426
9   0.0320   0.5     9.0  3.736510
11  0.0321   0.5     9.0  3.745073
13  0.0322   0.5     9.0  3.844520
7   0.0316   0.5     9.0  3.890370
8   0.0320   0.5     8.0  3.892654
0   0.0319   0.5     8.0  3.892806
10  0.0321   0.5     8.0  3.905720
2   0.0318   0.5     8.0  3.915657
17  0.0324   0.5     9.0  3.936207
15  0.0323   0.5     9.0  3.948039
4   0.0317   0.5     8.0  3.961478
12  0.0322   0.5     8.0  3.962130
6   0.0316   0.5     8.0  3.967480
16  0.0324   0.5     8.0  3.967735
14  0.0323   0.5     8.0  3.969873

"""
eps1 = [0.0319, 0.0318, 0.0317, 0.0316, 0.032, 0.0321, 0.0322, 0.0323, 0.0324]
eps2 = [0.5]
minpts = [8, 9]

# Initialize dataframe to organize scores
df_scores = pd.DataFrame(columns=["eps1", "eps2", "minpts", "score"])

for a in eps1:
    for b in eps2:
        for c in minpts:
            print("Now working on: eps1 " + str(a) + " eps2 " + str(b) + " minpts " + str(c))

            st_dbscan = st.ST_DBSCAN(eps1 = a, eps2 = b, min_samples = c)
            st_dbscan.fit(data_normed)
            labels = st_dbscan.labels
            # remove outliers (-1)
            # create mask
            mask = labels > -1
            labels_nooutliers = labels[mask]
            data_normed_nooutliers = data_normed[mask]
            score = davies_bouldin_score(data_normed_nooutliers, labels_nooutliers)
            df_scores.loc[len(df_scores)] = [a, b, c, score]

            print("Score: " + str(score))

print(df_scores)

#now = datetime.now().strftime("%M")
with open("C:/meg/params/1211_st_dbscan/scores_saved.pkl", "wb") as f:
   pickle.dump(df_scores, f)



# %%
#----- RUN WITH BEST PARAMETERS -----

best_eps1 = 0.0319
best_eps2 = 0.5
best_minpts = 9

# This will be useful later on
filename = "8-30Hz_bestparams_" + str(best_minpts) + "_" + str(best_eps1) + "_" + str(best_eps2)

#%%
st_dbscan = st.ST_DBSCAN(eps1 = best_eps1, eps2 = best_eps2, min_samples = best_minpts) 
st_dbscan.fit(data_normed)
mylabels = st_dbscan.labels

with open("C:/meg/params/labels_" + filename + ".pkl", "wb") as f:
    pickle.dump(mylabels, f)



#%%
#----- PREPARE LABELS -----
best_eps1 = 0.0319
best_eps2 = 0.5
best_minpts = 9
filename = "lh_8-30Hz_bestparams_" + str(best_minpts) + "_" + str(best_eps1) + "_" + str(best_eps2)

with open("C:/meg/params/03_lh_rh_rerun/labels_" + filename + ".pkl", "rb") as f:
   mylabels = pickle.load(f)

#%%
#----- VIEW DATA -----

# This code is partly based on https://github.com/eren-ck/st_dbscan
# Plots all data points for all subjects and timepoints, coloured by label
def plot(data, labels, savedir = "C:/meg/params/1211_st_dbscan/" + filename + ".png"):
    fig = plt.figure()
    ax = fig.add_subplot(1, 2, 2, projection='3d')

    colors = ["#F80606",'#1f78b4','#33a02c','#ff7f00','#6a3d9a','#b2df8a','#fb9a99','#a6cee3','#fdbf6f','#cab2d6',]
    #colors = ['#00000000','#00000000','#00000000','#ff7f00'] 
    #colors= ['#00000000','#00000000','#33a02c']

    # For every label: 
    # Choose a colour for the label
    # Pick out all the rows in the data that have this label
    # Plot everything for this label
    # Move on to next label
    for i in range(-1, len(set(labels))):
        if i == -1:
            continue # does not print noise; alternatively, you could colour noise black: col = [0, 0, 0, 1]
        else:
            col = colors[i % len(colors)]
        
        clust = data[np.where(labels==i)]
        
        ax.scatter(xs = clust[:,0], ys = clust[:,1], zs = clust[:,2], c=[col], s = 0.1, marker = '.')

    ax.set_zlabel("z (up)")
    ax.set_xlabel("x (right), on lh")
    ax.set_ylabel("y (front)")
    # https://matplotlib.org/stable/api/toolkits/mplot3d/view_angles.html
    #ax.view_init(elev=30, azim=-80, roll=0)

    # Add a freesurfer brain on the side to be helpful: 
    coords, faces = mne.read_surface("C:/meg/params/fs_subjects/fsaverage/surf/lh.inflated")
    sulc = fs.read_morph_data("C:/meg/params/fs_subjects/fsaverage/surf/lh.sulc")
    ax2 = fig.add_subplot(1, 2, 1, projection='3d')
    ax2.scatter(coords[:, 0], coords[:, 1], coords[:, 2], c=sulc, cmap='Greys', s=0.2)
    ax2.axis('off')

    fig.tight_layout()
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)

plot(data[:, 1:], mylabels)





# %%
#----- LEARN ABOUT LABELS ------

def percentage_table(arr):
    total = len(arr)
    freq = Counter(arr)
    table = [(num, (count / total) * 100) for num, count in freq.items()]
    table.sort(key=lambda x: -x[1])
    return table

arr = mylabels
for num, perc in percentage_table(arr):
    print(f"{num}: {perc:.2f}%")


#%%
#----- COLOUR BIG CLUSTERS BY FREQUENCY -----

# Extract just data associated with red
mask = mylabels == 0 # red label
labels_red = mylabels[mask]
data_red = data[mask]

# Extract just data associated with green
mask = mylabels == 2 # green label
labels_green = mylabels[mask]
data_green = data[mask]

# Plot and colour by frequency
def plot_color_by_freq(data, savedir): 
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
   
    ax.scatter(xs = data[:, 1], ys = data[:, 2], zs = data[:, 3], c = data[:, 0], cmap = 'viridis', s = 0.1)

    ax.set_zlabel("z (up)")
    ax.set_xlabel("x (right), on lh")
    ax.set_ylabel("y (front)")
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)
    
plot_color_by_freq(data_green, "C:/meg/params/1211_st_dbscan/" + filename + "_green.png")
# %%
