"""
This script uses the pkl file previously generated by individual_spread

"""

#%%

# User input
hemi = "lh"
base_dir = "C:/meg/params/03_lh_rh_rerun"

# Import packages
import mne
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.neighbors import NearestNeighbors
import sys
import math as math
import nibabel.freesurfer.io as fs
from collections import Counter
from sklearn.metrics import silhouette_score, davies_bouldin_score
import pathlib as Path
import os
from collections import Counter
sys.path.append(os.path.join(base_dir, "python_scripts"))
import st_dbscan as st


# %%
#----- LOAD DATAFRAMES -----
# Load dataframe created in individual_spread.py
# This contains coordinates (x, y, and z) representing the center of mass for all subjects and frequencies 

# NORMALIZED DATA
with open(os.path.join(base_dir, f"COM_coord_subject_df_8_to_30_normalized_{hemi}.pkl"), "rb") as f:
   COM_coord_subject_df_normalized = pickle.load(f)

# Extract 7 young subjects
#subjects_list = ['420143', '721377', '221585', '410084', '321585', '110101', '110126'] #best
subjects_list = ["110033", "110037", "110045", "110056", "110087", "110098", "120120"]
COM_coord_subject_df_normalized_subjectsample = COM_coord_subject_df_normalized[COM_coord_subject_df_normalized['subject'].isin(subjects_list)]

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data_normed = COM_coord_subject_df_normalized_subjectsample.loc[:, ['freq','x','y','z']].values

# UNNORMALIZED DATA
with open(os.path.join(base_dir, f"COM_coord_subject_df_8_to_30_{hemi}.pkl"), "rb") as f:
   COM_coord_subject_df = pickle.load(f)
COM_coord_subject_df_subjectsample = COM_coord_subject_df[COM_coord_subject_df['subject'].isin(subjects_list)]

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data = COM_coord_subject_df_subjectsample.loc[:, ['freq','x','y','z']].values


# %%
#----- RUN WITH BEST PARAMETERS -----
		
best_eps1 = 0.25
best_eps2 = 2.5
best_minpts = 10

# This will be useful later on
filename = "7subjects_v2_8-30Hz_bestparams_" + str(best_minpts) + "_" + str(best_eps1) + "_" + str(best_eps2)

st_dbscan = st.ST_DBSCAN(eps1 = best_eps1, eps2 = best_eps2, min_samples = best_minpts) 
st_dbscan.fit(data_normed)
mylabels = st_dbscan.labels

with open(f"{base_dir}/dbscan/labels_{filename}.pkl", "wb") as f:
    pickle.dump(mylabels, f)

#with open(f"{base_dir}/labels_7subjects_8-30Hz_bestparams_10_0.25_2.5.pkl", "rb") as f:
#   mylabels = pickle.load(f)

#%%
#----- VIEW DATA -----

#with open(f"{base_dir}/dbscan/labels_7subjects_8-30Hz_bestparams_10_0.25_2.5.pkl", "rb") as f:
#   mylabels = pickle.load(f)

# This code is partly based on https://github.com/eren-ck/st_dbscan
# Plots all data points for all subjects and timepoints, coloured by label
def plot(data, labels, savedir = f"{base_dir}/dbscan/" + filename + ".png"):
    fig = plt.figure()
    ax = fig.add_subplot(1, 2, 2, projection='3d')

    colors = ["#F80606",'#1f78b4','#33a02c','#ff7f00','#6a3d9a','#b2df8a','#fb9a99','#a6cee3','#fdbf6f','#cab2d6',]
    #colors = ['#00000000','#00000000','#00000000','#ff7f00'] 
    #colors= ['#00000000','#00000000','#33a02c']

    # For every label: 
    # Choose a colour for the label
    # Pick out all the rows in the data that have this label
    # Plot everything for this label
    # Move on to next label
    for i in range(-1, len(set(labels))):
        if i == -1:
            col = [0, 0, 0, 1]
        else:
            col = colors[i % len(colors)]
        
        clust = data[np.where(labels==i)]
        
        ax.scatter(xs = clust[:,0], ys = clust[:,1], zs = clust[:,2], c=[col], s = 2, marker = '.')

    ax.set_zlabel("z (up)")
    ax.set_xlabel("x (right), on lh")
    ax.set_ylabel("y (front)")
    # https://matplotlib.org/stable/api/toolkits/mplot3d/view_angles.html
    #ax.view_init(elev=30, azim=-80, roll=0)

    # Add a freesurfer brain on the side to be helpful: 
    coords, faces = mne.read_surface("C:/meg/params/fs_subjects/fsaverage/surf/lh.inflated")
    sulc = fs.read_morph_data("C:/meg/params/fs_subjects/fsaverage/surf/lh.sulc")
    ax2 = fig.add_subplot(1, 2, 1, projection='3d')
    ax2.scatter(coords[:, 0], coords[:, 1], coords[:, 2], c=sulc, cmap='Greys', s=0.2)
    ax2.axis('off')

    fig.tight_layout()
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)

plot(data[:, 1:], mylabels)





# %%
#----- LEARN ABOUT LABELS ------

def percentage_table(arr):
    total = len(arr)
    freq = Counter(arr)
    table = [(num, (count / total) * 100) for num, count in freq.items()]
    table.sort(key=lambda x: -x[1])
    return table

arr = mylabels
for num, perc in percentage_table(arr):
    print(f"{num}: {perc:.2f}%")


#%%
#----- COLOUR BIG CLUSTERS BY FREQUENCY -----

# Extract just data associated with red
mask = mylabels == 0 # red label
labels_red = mylabels[mask]
data_red = data_normed[mask]

# Extract just data associated with green
#mask = mylabels == 2 # green label
#labels_green = mylabels[mask]
#data_green = data[mask]

# Plot and colour by frequency
def plot_color_by_freq(data, savedir): 
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
   
    ax.scatter(xs = data[:, 1], ys = data[:, 2], zs = data[:, 3], c = data[:, 0], cmap = 'viridis', s = 2)

    ax.set_zlabel("z (up)")
    ax.set_xlabel("x (right), on lh")
    ax.set_ylabel("y (front)")
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)
    
plot_color_by_freq(data_red, f"{base_dir}/dbscan/" + filename + "_red.png")
# %%
