"""
This script uses the pkl file previously generated by individual_spread
"""

#%%

# User input
segment_type = "first15"
hemi = "lh"
base_dir = "C:/meg/params/05_omega"
grid_search = False


# Import packages
import mne
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.neighbors import NearestNeighbors
import sys
import math as math
import nibabel.freesurfer.io as fs
from collections import Counter
from sklearn.metrics import silhouette_score, davies_bouldin_score
import pathlib as Path
import os
sys.path.append(os.path.join(base_dir, "python_scripts"))
import st_dbscan as st
from collections import Counter

id = f"{segment_type}_{hemi}"

# %%
#----- LOAD DATAFRAMES -----
# Load dataframe created in individual_spread.py
# This contains coordinates (x, y, and z) representing the center of mass for all subjects and frequencies 

# NORMALIZED DATA
with open(os.path.join(base_dir, f"COM_coord_subject_df_8_to_30_{id}_normalized.pkl"), "rb") as f:
   COM_coord_subject_df_normalized = pickle.load(f)

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data_normed = COM_coord_subject_df_normalized.loc[:, ['freq','x','y','z']].values

# UNNORMALIZED DATA
with open(os.path.join(base_dir, f"COM_coord_subject_df_8_to_30_{id}.pkl"), "rb") as f:
   COM_coord_subject_df = pickle.load(f)

# Transform to numpy array; necessary for next steps
# Remove column for subjects since that's what they did in example
data = COM_coord_subject_df.loc[:, ['freq','x','y','z']].values

#%%
#----- CHOOSE STARTING PARAMETERS FOR ST-DBSCAN -----
"""
SOURCES: 
Function I am using: https://github.com/eren-ck/st_dbscan
Original paper: https://doi.org/10.1016/j.datak.2006.01.013

ST-DBSCAN requires the following parameters: 
eps1 = distance, spatial
eps2 = distance, time
minpts = min number of points within eps1 and eps2 distance of a point. "dense" = greater than minpts
The original dbscan paper also lists a parameter called delta_eps, but the python function does not

CHOOSING PARAMETERS: 
Use the heuristic method described in the original paper.
This method involves first defining minpts, then using minpts to find eps

0. minpts = ln(n) where n is size of database
"""
if grid_search: 
    n = len(data_normed) 
    print(n)
    minpts = int(math.log(n))
    print(minpts)
"""
1. Determine the distances to the k-nearest neighbors for each object, where k is equal to minpts
https://scikit-learn.org/stable/modules/neighbors.html#finding-the-nearest-neighbors
*distance array: note that the nearest neighbor of each point is the point itself, hence the 0s
2. Sort k-distance values in descending order
3. Determine elbow
4. Select eps to less than the distance defined at the elbow
"""
if grid_search: 
    # To obtain eps1 (i.e., spatial), use the heuristic algorithm:
    input = data_normed[:, 1:] # exclude the first two columns (subject and frequency)
    nbrs = NearestNeighbors(n_neighbors = minpts, algorithm = "ball_tree").fit(input)
    # metric = metric used for pairwise distances - using default minkowski (euclidean distance)
    # algorithm = ball_tree (constructs a tree where each node is ball enclosing subset of points)
    distances, indices = nbrs.kneighbors(input)
    # distances is an array with int(minpts) number of columns
    # unfold the array, then sort everything (removing zeros makes it easier to read the plot)
    sorted_distances = np.trim_zeros(np.sort(distances.flatten()))[::-1]
    # Plot
    plt.plot(sorted_distances)
    #plt.xlim(0, 10000)
    #plt.ylim(0.02, 0.05)
    plt.grid()

# %%
#----- CHOOSE PARAMETERS -----

def most_frequent_fraction(arr):
    counts = Counter(arr)
    total = len(arr)
    sorted_counts = sorted(counts.values(), reverse=True)
    return [count / total for count in sorted_counts[:3]]

if grid_search:

    eps1 = list(np.arange(0.0365, 0.038, 0.0001))
    eps2 = [0.25, 0.5, 0.75]
    minpts = [3, 4, 5, 6, 7, 8, 9]

    # Initialize dataframe to organize scores
    df_scores = pd.DataFrame(columns=["eps1", "eps2", "minpts", "score", "percent_nonoutliers", "largest_group", "2nd_largest_group", "3rd_largest_group"])

    for a in eps1:
        for b in eps2:
            for c in minpts:
                print("Now working on: eps1 " + str(a) + " eps2 " + str(b) + " minpts " + str(c))

                st_dbscan = st.ST_DBSCAN(eps1 = a, eps2 = b, min_samples = c)
                st_dbscan.fit(data_normed)
                labels = st_dbscan.labels
                # remove outliers (-1)
                # create mask
                mask = labels > -1
                labels_nooutliers = labels[mask]
                data_normed_nooutliers = data_normed[mask]
                score = davies_bouldin_score(data_normed_nooutliers, labels_nooutliers)
                df_scores.loc[len(df_scores)] = [a, b, c, score, len(labels[mask])/len(data_normed), most_frequent_fraction(labels)[0], most_frequent_fraction(labels)[1], most_frequent_fraction(labels)[2]]

                print("Score: " + str(score))

    pd.set_option('display.max_rows', None)
    print(df_scores)
    df_scores.to_csv("C:/meg/params/05_omega/dbscan/full_lh_gridsearch_scores.csv")

    #now = datetime.now().strftime("%M")
    with open(f"{base_dir}/dbscan/scores_saved_{id}.pkl", "wb") as f:
        pickle.dump(df_scores, f)


# %%
#----- SET PARAMETERS FROM LH -----
best_eps1 = 0.0376
best_eps2 = 0.25
best_minpts = 9

# This will be useful later on
filename = f"{id}_8-30Hz_bestparams_" + str(best_minpts) + "_" + str(best_eps1) + "_" + str(best_eps2)
print(filename)

#%%
#----- DBSCAN -----

st_dbscan = st.ST_DBSCAN(eps1 = best_eps1, eps2 = best_eps2, min_samples = best_minpts) 
st_dbscan.fit(data_normed)
mylabels = st_dbscan.labels

with open(f"{base_dir}/dbscan/labels_" + filename + ".pkl", "wb") as f:
    pickle.dump(mylabels, f)



#%%
#----- PREPARE LABELS -----

with open(f"{base_dir}/dbscan/labels_" + filename + ".pkl", "rb") as f:
   mylabels = pickle.load(f)

#----- LEARN ABOUT LABELS ------

def percentage_table(arr):
    total = len(arr)
    freq = Counter(arr)
    table = [(num, (count / total) * 100) for num, count in freq.items()]
    table.sort(key=lambda x: -x[1])
    return table

for num, perc in percentage_table(mylabels):
    print(f"{num}: {perc:.2f}%")

#------ CREATE INFO TEXT FOR TITLE ------
N_subjects = round(len(COM_coord_subject_df_normalized)/len(pd.unique(COM_coord_subject_df_normalized["freq"])))
large_cluster_name = str(percentage_table(mylabels)[0][0])
large_cluster_size = str(round(percentage_table(mylabels)[0][1], 2))
medium_cluster_name = str(percentage_table(mylabels)[1][0])
medium_cluster_size = str(round(percentage_table(mylabels)[1][1], 2))
small_cluster_name = str(percentage_table(mylabels)[2][0])
small_cluster_size = str(round(percentage_table(mylabels)[2][1], 2))
title = f"Params: eps1 {best_eps1}, eps2 {best_eps2}, minpts {best_minpts}\n N_subjects: {N_subjects} \n Largest: {large_cluster_name}: {large_cluster_size}% \n 2nd-largest: {medium_cluster_name}: {medium_cluster_size}% \n 3rd-largest: {small_cluster_name}: {small_cluster_size}%"

#----- VIEW DATA -----
#import matplotlib
#matplotlib.use("Qt5Agg")
#from matplotlib.backends.backend_qt5agg import FigureCanvas
#from matplotlib.figure import Figure
# This code is partly based on https://github.com/eren-ck/st_dbscan
# Plots all data points for all subjects and timepoints, coloured by label
def plot(data, labels, savedir = f"{base_dir}/dbscan/" + filename + ".png"):
    fig = plt.figure()
    ax = fig.add_subplot(1, 2, 2, projection='3d')

    colors = ["#F80606",'#33a02c', '#1f78b4','#ff7f00','#6a3d9a','#b2df8a','#fb9a99','#a6cee3','#fdbf6f','#cab2d6',]
    #colors = ['#00000000','#00000000','#00000000'] 
    #colors= ['#00000000','#00000000','#33a02c']

    # For every label: 
    # Choose a colour for the label
    # Pick out all the rows in the data that have this label
    # Plot everything for this label
    # Move on to next label
    for i in range(-1, len(set(labels))):
        if i == -1:
            col = [0, 0, 0, 1] #continue # does not print noise; alternatively, you could colour noise black: 
        else:
            col = colors[i % len(colors)]
        
        clust = data[np.where(labels==i)]
        
        ax.scatter(xs = clust[:,0], ys = clust[:,1], zs = clust[:,2], c=[col], s = 0.1, marker = '.')

    ax.set_zlabel("z (up)")
    ax.set_xlabel(f"x (right), on {hemi}")
    ax.set_ylabel("y (front)")
    ax.set_xlim(-40, 40)
    ax.set_ylim(-100, 100)
    ax.set_zlim(-75, 75)
   #  https://matplotlib.org/stable/api/toolkits/mplot3d/view_angles.html
    if hemi == "rh":
        ax.view_init(azim=250)
    ax.set_title(title)

    # Add a freesurfer brain on the side to be helpful: 
    coords, faces = mne.read_surface(f"C:/meg/params/fs_subjects/fsaverage/surf/{hemi}.inflated")
    sulc = fs.read_morph_data(f"C:/meg/params/fs_subjects/fsaverage/surf/{hemi}.sulc")
    ax2 = fig.add_subplot(1, 2, 1, projection='3d')
    ax2.scatter(coords[:, 0], coords[:, 1], coords[:, 2], c=sulc, cmap='Greys', s=0.2)
    ax2.axis('off')
    ax2.set_xlim(-40, 40)
    ax2.set_ylim(-100, 100)
    ax2.set_zlim(-75, 75)
    if hemi == "rh":
        ax2.view_init(azim=250)
    
    fig.tight_layout()
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)

plot(data[:, 1:], mylabels)





#%%
#----- COLOUR BIG CLUSTERS BY FREQUENCY -----

# Extract just data associated with green
#mask = mylabels == 4
#labels_masked = mylabels[mask]
#data_masked = data[mask]

# Plot and colour by frequency
def plot_color_by_freq(data, savedir): 
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
   
    ax.scatter(xs = data[:, 1], ys = data[:, 2], zs = data[:, 3], c = data[:, 0], cmap = 'viridis', s = 0.1)

    ax.set_zlabel("z (inferior-superior)")
    #ax.set_xlabel(f"x (right), on {hemi}")
    ax.set_ylabel("y (posterior-anterior)")
    ax.set_xlim(-100, 100)
    ax.set_xticks([])
    ax.set_xticklabels([])
    ax.set_ylim(-100, 100)
    ax.set_yticks([-50, 0, 50])
    ax.set_yticklabels(["-50", "0", "50"])
    ax.set_zlim(-100, 100)
    ax.set_zticks([-50, 0, 50])
    ax.set_zticklabels(["-50", "0", "50"])
    ax.set_box_aspect((1, 1, 1))
    if hemi == "lh": 
        ax.view_init(azim=180, elev=0)
    else: 
        ax.view_init(azim=360, elev=0)
    ax.set_title("lh first15")
    fig.savefig(savedir, dpi=300, bbox_inches="tight", pad_inches=1)
    plt.ion()
    
plot_color_by_freq(data, f"{base_dir}/dbscan/" + filename + "_large.png")


# %%
# EXTRA HELPER

import mne
stc = mne.read_source_estimate("C:/meg/params/mean_stc")
stc.plot(
    subject = "fsaverage", 
    subjects_dir = "C:/meg/params/fs_subjects", 
    time_viewer = True, 
    hemi = "rh"
)
# %%
